services:
  - type: web
    name: trading-journal
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NOTION_API_KEY
        value: ntn_Q38234662644sLexkBRmI46birmVGxUHESVj8PrVosR0Oi
      - key: NOTION_DATABASE_ID
        value: 3bf0e3e57718801182ece24131bad598
      - key: GEMINI_API_KEY
        sync: false
